
# This is a comment line
# Sample makefile for fraction class



make: stats.cc stattest.cc stats.h
	g++ -Wall -c stats.cc
	g++ -Wall -c stattest.cc
	g++ stattest.o stats.o -o stattest 

clean:
	rm *.o 
